# Generated by Django 5.0.4 on 2024-05-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=100)),
                ('years_experience', models.CharField(max_length=100)),
                ('education_level', models.CharField(max_length=100)),
                ('industry', models.CharField(max_length=100)),
            ],
        ),
    ]
